### ISSUE TITLE
Distance Units ignored by web app

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-Monitoring-System-3#115]
User adrianco reports

I have distance units set to Miles in the Vehicle option. I'd also like F rather than C for temperature as that's what the car itself displays. The dashboard in the webapp shows everything in Km and C.

**Comment by adrianco** [comment]
Tesla Roadster, latest version of code as of May 6th, I had just updated it.

**Comment by markwj** [comment]
Duplicate of issue:

https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/52
