### ISSUE TITLE
Adding or merging local fork with master ?

### ISSUE THREAD

**Issue by prensel** [openvehicles/Open-Vehicle-Monitoring-System-3#141]
I'm working on my local fork repo on an addition for the Zeva BMS.
How can i push or integrate this into the master repo ?

**Comment by markwj** [comment]
Usual mechanism is to send a PULL request to the master project. You can also let the developers mailing list know what you are working on, and what you have done, so we can speed-up the merge. So long as your changes are purely to the ZEMA vehicle module, merging can be quick and simple.
