### ISSUE TITLE
Calibrate 12V reading?

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#147]
The 12V aux battery reading from a Nissan LEAF from OVMS is lower than the actual voltage. As measured using a voltmeter. This is probably no fault of OVMS, we're just reading what on the CAN bus right? Has anyone else noticed/experienced this? Is there anyway to apply a calibration factor?

**Comment by M4GNV5** [comment]
The 12V voltage is measured using the incoming voltage that powers the OVMS. You can calibrate it using 
```
config set system.adc factor12v <factor>
```
the `<factor>` has to be calculated using: `oldFactor * (displayedVoltage / actualVoltage)`.
- `oldFactor` is the old value set. If you have not changed it yet it is `195.7`
- `displayedVoltage` is the Voltage as displayed by the OVMS.
- `actualVoltage` is the Voltage as measured bu hand using a voltmeter.

**Comment by dexterbg** [comment]
I've added a section to the user guide:
https://docs.google.com/document/d/16JrXR7rybp-18DrEoeh1rg6GqQT_jVBvhaXh2oEWRHw/edit#heading=h.usa0sgzemy9l

**Comment by glynhudson** [comment]
Awesome! Thanks 👍

**Comment by glynhudson** [comment]
Assuming the `config set` command is issued via the SHELL page on the module webpage?

**Comment by cavram** [comment]
You can also issue commands via the app messages screen.

Try "ME   L" an abbreviation for metrics list. It's not case sensitive.

Also try ?
Or "me?" Com and completion.

Chris Avram

On 2 Aug. 2018 10:17 am, "Glyn Hudson" <notifications@github.com> wrote:

Assuming the config set command is issued via the SHELL page on the module
webpage?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/issues/147#issuecomment-409765327>,
or mute the thread

**Comment by dexterbg** [comment]
…or you can send commands from my server based shell if you're on my server (https://dexters-web.de/), or you can send commands via ssh shell or the USB terminal. The server shell works like the app shell, so will work via modem as well as wifi. The builtin web and ssh servers are currently only available via wifi.

But please note: commands **are** case sensitive in v3 now (they haven't been in v2).

**Comment by glynhudson** [comment]
Awesome, that's great to know that shell commands can be issued via the server remotely. 

I've just tried to issue to command via the local web server connected via station WiFi to the module. The command does not seem to have been applied. Should there be some sort of confirmation? 

![screenshot 2018-08-02 at 22 57 10](https://user-images.githubusercontent.com/758844/43613527-9d8054ce-96a7-11e8-9b4a-b2b3a0d24c81.png)

**Comment by dexterbg** [comment]
See above, the command is `config set system.adc factor12v <factor>`.

Also see `config ?`, `config list`, `config list ?` and `config list system.adc`. Configuration is segmented into "params" (categories) with "instances" (variables).

**Comment by slcasner** [comment]
The "Usage" line _was_ the response from the command interpreter.  It
was telling you that the input did not fit the required command syntax
as shown.  This follows a convention from Unix-like systems.  It is
sufficient to remind a user who knows the command how to use it, but
obviously falls short of being a user guide for the command.

Michael explained this command in more detail.

                                                        -- Steve

**Comment by glynhudson** [comment]
Doh! Sorry my mistake, that's much better 👍 

![screenshot 2018-08-03 at 00 01 35](https://user-images.githubusercontent.com/758844/43615612-66747c04-96b0-11e8-9699-14fbb78197ba.png)
