### ISSUE TITLE
2011 Nissan Leaf SOC show 0%

### ISSUE THREAD

**Issue by izmopa** [openvehicles/Open-Vehicle-Monitoring-System-3#154]
All other fuctions works in my Nissan Leaf and OVMS 3.1 but soc shows allways 0%
When I give command metrics list in shell I see that 
xnl.v.b.soc.newcar shows correct soc value but
v.b.soc is 0%
Other Leaf values are correct. How to change OVMS android application to use xnl.v.b.soc.newcar value?
Thanks from info. Great product!

**Comment by glynhudson** [comment]
Have you got the OVMS connected directly to the car's ODBII port? 

I had the same issue (SOC 0%) when connecting the OVMS via a ODBII extension cable. When I connected the unit directly it read the SOC fine. I assumed this must have been something to do with poor quality wiring of the ODBII extension.

**Comment by izmopa** [comment]
Thanks from answer. I use Nissan Leaf OBD-II to DB9 Data Cable for OVMS  (fromFasttech). What do you mean direct connection? Is there other connector to connect OVMS module to car?

**Comment by glynhudson** [comment]
By direct I mean plugging the OVMS cable directly into the odb2 port rather
than using an extension. Cable. It sounds like your doing this already.

- sent from my mobile device

**Comment by carrott** [comment]
@izmopa 
Set the _xnl soc.newcar_ configuration to _true_ to use the alternative soc calculation. Set _xnl maxGids_ to taste to set the 100% level, the default is 281 corresponding to a new 24kWh car.

There OVMS uses two methods to obtain the SoC from the car. The default method gets the SoC directly from the car as a percentage of the current battery capacity. It would seem that our implementation of this method doesn't work on older vehicles. The other method uses the car's current measure of energy stored in the battery (i.e. the GIDs that LeafSpy shows) as a percentage of the configured maxGids value.

@glynhudson 
Most of the data the OVMS Leaf module consumes comes from the EV can bus which isn't on the 'normal' OBDDII pins. If your extension doesn't pass those pins through then lots of things won't work.

**Comment by izmopa** [comment]
Thanks from info! That worked to me to get SOC to Android app. Here is shell commands that I did and then I rebooted OVMS if someone other needs this.
**OVMS# config set xnl soc.newcar true
Parameter has been set.
OVMS# config set xnl maxGids 281
Parameter has been set.**

Homelink commands works in my car to start/stop A/C even if its 2011 model. and I have not switched of Telematics box.

**Comment by glynhudson** [comment]
>Most of the data the OVMS Leaf module consumes comes from the EV can bus which isn't on the 'normal' OBDDII pins. If your extension doesn't pass those pins through then lots of things won't work.

Thanks, that would explain what I experienced. 

>The OVMS uses two methods to obtain the SoC from the car. The default method gets the SoC directly from the car as a percentage of the current battery capacity. It would seem that our implementation of this method doesn't work on older vehicles. The other method uses the car's current measure of energy stored in the battery (i.e. the GIDs that LeafSpy shows) as a percentage of the configured maxGids value. I have a 2012 which works with the second method, I'll see if I can make the first method work on it.

I have a 2014 24kw leaf and 2015 24kwh env200. For the record the SOC displayed worked with default settings.

**Comment by izmopa** [comment]
Just my little note to Maxgids. MaxGids value 281 is for new 24kWh indeed. If your Leaf SOH is 80% then you have to calculate correct MaxGids (281 * 0.8 = 225) that you get correct SOC value when you use alternative soc.newcar parameter to read SOC.

**Comment by amralomari** [comment]
My 2015 stopped showing the correct SOC (sometimes 0% sometimes some random number) after the latest firmware update.
I'll try this code

> OVMS# config set xnl soc.newcar true
Parameter has been set.
OVMS# config set xnl maxGids 281
Parameter has been set.

 then see if it'll work
