### ISSUE TITLE
Module crash when click Status in Console

### ISSUE THREAD

**Issue by mako19** [openvehicles/Open-Vehicle-Monitoring-System-3#155]
I'm running 3.1.0008 and the issue was there from start. Anytime I open the Console in my Chrome browser and click Status, the module crashes giving the following string: 
W (402576) websocket: WebSocketHandler[0x3f81b2f0]: job queue overflow detected

It must be power-cycled to get running again. This is very frustrating. Chrome F12 debug gives this:

Failed to load resource: the server responded with a status of 403 (Forbidden)
/#/cfg/vehicle:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
script.js:137

**Comment by dexterbg** [comment]
The websocket warning is not the crash message, the crash message contains a crash reason and a backtrace, please provide that. If you're connected to a v2 server you should find it in your "*-OVM-DebugCrash" table, else you will need to connect a USB terminal to see that message.

**Comment by dexterbg** [comment]
Lack of details…
