### ISSUE TITLE
Nissan Leaf 2011-2012 EV system activation request signal connection

### ISSUE THREAD

**Issue by izmopa** [openvehicles/Open-Vehicle-Monitoring-System-3#156]
My Nissan Leaf 2011 needs EV system activation request signal to get A/C climate control on/off when car is not charging. I know TCU PIN11 12V can activate EV system (My TCU is disconnected). Is this supported in OVMS 3.1 hardware /software? I can't find is there 12V on/off pin in DA26 connector? Is there DA26pin pinouts document?

**Comment by dalathegreat** [comment]
@dexterbg I suggest we close this one and solve it in #607 instead!
