### ISSUE TITLE
30Kwh Nissan Leaf with battery update shows 0% SOH

### ISSUE THREAD

**Issue by ankohanse** [openvehicles/Open-Vehicle-Monitoring-System-3#162]
Not sure if this is the right platform for this question, I am a newby to all this OVMS stuff...

Bought and installed a OVMS v3 module and installed it in the car (2015 Nissan Leaf 30KWh , Japanese Domestic Market model imported to New Zealand) via the Nissan Leaf OBD-II to DB9 Data Cable for OVMS (from Fasttech). Install was pretty straightforward, so great work done by all of you!

Most metrics show up in the Status screen when I log into http://192.168.4.1 or view it in the Android app. However, I miss some metrics that are available in LeafSpy (so would expect them to be able to be retrieved via the ODBD II port). Typically:
- v.b.soh    (battery State of Health)
- v.b.cac    (battery Hx)
- v.tp.*      (tyre pressure)

Most other metrics that I expect are there, so the connection between module and car should be ok?

**OVMS#** metrics list v.b
v.b.12v.current
v.b.12v.voltage                          12.19V
v.b.12v.voltage.alert
v.b.12v.voltage.ref                      12.6V
v.b.c.level.avg
v.b.c.level.max
v.b.c.level.min
v.b.c.level.stddev
v.b.cac
v.b.consumption                          0Wh/km
v.b.coulomb.recd
v.b.coulomb.used
v.b.current                              1A
v.b.energy.recd
v.b.energy.used
v.b.health
v.b.power
v.b.range.est
v.b.range.full
v.b.range.ideal                          121.552km
v.b.soc                                  64%
v.b.soh
v.b.temp                                 21°C
v.b.voltage                              369.5V
xnl.v.b.gids                             214
xnl.v.b.hx                               0
xnl.v.b.soc.instrument                   64%
xnl.v.b.soc.newcar                       60.1124%

Are the missing metrics simply not yet implemented/supported on the v3 module (still using the v2 server connection), or am I doing something wrong?

Thanks, Anko

![android vehicle info](https://user-images.githubusercontent.com/11971893/47263516-79fc7e00-d55f-11e8-8e73-228937854142.png)

**Comment by carrott** [comment]
Hi Anko,

I understand that the Japanese cars don't have tyre pressure sensors which is why that doesn't work.

However on my 2012 and 2016 JDM Leafs the SOH does work. I see you have 3.1.010 which looks like it should have the latest Leaf features. I'm running a slightly older version of the rest of the framework so it's possible something has broken.

I won't be able to test with the latest code until next weekend, I'll get back to you then with some further diagnostics.

P.S. v.b.cac now returns the amp hour capacity, and hx is in xnl.v.b.hx

**Comment by ankohanse** [comment]
Thanks for that.

Meanwhile, I gave the module another reboot and re-checked my config settings:
OVMS# config list xnl
xnl (readable writeable)
   maxGids: 356
   modelyear: 2015

Soo looks to be set ok, but unfortunately it is still not returning cac, hx and soh

So took the additional step of inserting an SD-card into the module and configured logging to /sd/logs/log:
OVMS# config list log
log (readable writeable)
   file.enable: yes
  file.maxsize: 1024
   file.path: /sd/logs/log
   level: info
   level.v-nissanleaf: verbose

And did another reboot…. After that I can see the log growing with all kind of components log lines.
Did not yet see a v-nissanleaf line occur in the log, but will keep an eye on it over the next week or so.

I also had a look into the code in github (https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/blob/master/vehicle/OVMS.V3/components/vehicle_nissanleaf/src/vehicle_nissanleaf.cpp).
The properties I miss exactly match all the properties that are set inside function OvmsVehicleNissanLeaf::PollReply_Battery.

I could think of 2 reasons for this function to fail:

  1.  reply_len is not equal to 39 for my 2015 30kwh JDM.
In that case I should at some point see the trace
     ESP_LOGI(TAG, "PollReply_Battery: len=%d != 39", reply_len);


  1.  The function PollReply_Battery itself never gets called.
That would somehow mean that IncomingPollReply never gets called with pid=-0x01
Any way of recognizing this in the trace?

Cheers,
Anko

**Comment by carrott** [comment]
The SOH data is polled from the LBC and the poller is only enabled when the car is 'on', see line 586 of vehicle_nissanleaf.cpp. Does your v.e.on metric ever go to true?

**Comment by ankohanse** [comment]
Tested with parked, not charging car, turned on. As expected, v.e.on==true.
See attachment for all metrics (edited to mask the vin and the gps coordinates)

[metrics.txt](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/files/2527965/metrics.txt)

**Comment by imperialjoy** [comment]
I can confirm that my 2016 30kwh Japanese Leaf has the same issue, the soh metric is always 0.  I'm also in NZ :)

**Comment by carrott** [comment]
My test vehicle is a 2016 24kWh Japanese Leaf (also in New Zealand). 

I've just tested a local build of 3.1.010 and SOH is working on my setup.

We do have a bug which might be causing what you both are seeing, the MCP2515 CAN hardware stop working randomly. If you're using the Leaf specific cable then the 'EV' can bus is on the internal ESP32 CAN hardware and the 'Car' CAN bus is on a MCP2515. The SOH data is polled from the Car bus, so if the MCP2515 isn't working you won't see the SOH. The other symptom of this problem is that the odometer metric doesn't update since it comes from the Car bus too.

I just now unplugged my OVMS, turned the car on, and then plugged in the OVMS. The SOH and odometer were correctly read from the car.

Mark made some changes last week in 4060d4133102806e2b69cbea7c52dc863c608e60 to try to fix the MCP2515, I've just built a version with this change and I'll see if the external can buses work better now.

**Comment by ankohanse** [comment]
The issue might be specific to 30kwh Leafs that had the software update for the battery management system (to solve the issue with the incorrect/too negative reporting of SOH). 

Today I finally had a chance to download and inspect the logs that I had enabled 2 weeks ago. In there, I find many, many repeats of the following trace line:
     [0;32mI (25117791) v-nissanleaf: PollReply_Battery: len=41 != 39[0m

I very much hope that the first 39 bytes are unchanged and they just added 2 new values. Or maybe the corrected SOH will be in those 2 new values....   

In todays log, above several of those error trace lines, I do find the following trace:
     [0;32mI (70986481) ovms-server-v2: Send MP-0 PIOTA firmware 3.1.011 has been updated (OVMS will restart)[0m
That might have been the fix for MCP2515 you are mentioning? In that case, the update does not solve the issue and I do not expect it to solve it if the message contents have gone from 39 to 41 bytes.

What is the easiest way to dump the contents the error is triggered on, so that we can inspect the content of those 41 bytes and compare them to the 39 bytes we previously were used to get?
Can I ask you to add a debug or verbose level trace to these errors that will dump the binary content?
That would be a great tool for similar problems in the future, we would only need to enable logging to v-nissanleaf as debug or verbose instead of the normal info level.
Or is there a way already in the current firmware to do such content dumps?

I will also look into how to do a local compile and how then to deploy that to the module, but that is going to take me some time...

Attached todays log for reference

[log.20181111-093315.txt](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/files/2569032/log.20181111-093315.txt)

**Comment by imperialjoy** [comment]
I can confirm the soh is blank for me too, 30kwh Leaf 2016.  BMS update applied.

LeafSpy continued to work after the BMS software update, so I don't know if the BUS reporting it  actually changed.

metrics while plugged in and charging:

v.b.range.ideal                          98.576km
v.b.soc                                  63%
v.b.soh
v.b.temp                                 24°C
v.b.voltage                              368.5V
v.c.charging                             yes
v.c.climit                               15A
v.c.current                              7.5A

**Comment by imperialjoy** [comment]
I applied carrotts advice and unplugged, then plugged back in while the car was on.  The MQTT feed from the car shows a soh update while its driving, but the value is (null).

On a somewhat related note, which sim card and APN do you use in NZ?

**Comment by ankohanse** [comment]
Managed to capture the contents of the received bus message:
[0;32mI (46569481) webcommand: HttpCommandStream[0x3f81b418]: 4203420 bytes free, executing: can log trace 1:79b-7bb[0m
D (46569491) canlog: canlog Info * Type:trace; Path:''; Filter:1:79b-7bb; Vehicle:NL;[0m
V (46690631) canlog: RX can1 id 79b len 8: 02 21 01 00 00 00 00 00 | .!......[0m
V (46690641) canlog: RX can1 id 79b len 8: 30 00 19 00 00 00 00 00 | 0.......[0m
V (46690641) canlog: RX can1 id 7bb len 8: 10 2b 61 01 ff ff fc 4e | .+a....N[0m
V (46690651) canlog: RX can1 id 7bb len 8: 21 02 8a ff ff ff 46 ff | !.....F.[0m
V (46690681) canlog: RX can1 id 7bb len 8: 22 ff ff ff 12 90 2a f8 | ".....*.[0m
V (46690701) canlog: RX can1 id 7bb len 8: 23 8f cd 32 de 03 8b 00 | #..2....[0m
V (46690731) canlog: RX can1 id 7bb len 8: 24 5c 1f 3d 00 08 96 c6 | $\.=....[0m
V (46690761) canlog: RX can1 id 7bb len 8: 25 00 0b 32 90 80 00 01 | %..2....[0m
V (46690791) canlog: RX can1 id 7bb len 8: 26 00 00 ff ff ff ff ff | &.......[0m
[0;32mI (46690801) v-nissanleaf: PollReply_Battery: len=41 != 39[0m

Cleaned up with packet index numbers (21-26) removed and byte numbers added like was done within function PollRepy_Battery that gives:
> 0x79b 21 01
< 0x7bb 61 01
[ 0,, 5]  ff ff fc 4e    02 8a
[ 6..15] ff ff ff 46    ff ff ff ff    12 90 
[16..23] 2a f8 8f cd      32 de 03 8b      
[24..31] 00 5c     **1f 3d**     00 08 96 c6 
[32..38] 00 **0b 32 90**     80 00 01
[39..40] 00 00

(Note that the example in the code has as last line "[33..38]" which should be "[32..38]")

Following the code in PollReply_Battery that would result in:
hx = [26]<<8 + [27] = 0x1f3d =  7997
m_hx = hx / 100.0   --> 79,97

ah10000 = [33]<<16 + [34]<<8 + [35] = 0x0b3290 = 733840
cac = ah = ah10000 / 10000.0  ->  73.3840

SOH = ah / newCarAh * 100    where the newCarAh is not yet known for a 30kwh Leaf


Comparing to a LeafSpy also taken this morning:
hx = 78.10      (close!)
AHr = 73.38    (equal!)
SOH = 92.33%

Computing backward:
newCarAh30 = ah / soh * 100 = 73.38 / 92.33 * 100 = 79.48 ~ 80

Which sounds like a reasonable value as it is about 25% above the newCarAH of a 24kwh leaf (66 * 1.25 = 82.5)

So a fix for 30kwh Leafs would be to allow for a reply_len == 39 || reply_len==41 in PollReply_Battery and then set the following configs via the shell:

config set xnl maxGids 356
config set xnl modelyear 2015   (or 2016 or 2017)
config set xnl newCarAh 80

**Comment by ankohanse** [comment]
I've committed the (trivial) code change to git. Not sure whether just the commit is sufficient or if I also need to create a Pull Request to have it included in the next 3.1.012 OTA release?

**Comment by BrainBug0815** [comment]
I know this issue also from my Kia Soul EV. It (SOH) worked at my initial tests.
Somehow it stopped working for some time. Now it is working again.
I still have to find out the pattern. (plug in while ON/OFF/CHARGING, or something else)

Sadly, currently I only plug it in when I really need it to avoid the 12v Battery drain issue (battery is dead within 24 hours)

**Comment by ankohanse** [comment]
Fix will be included in firmware 3.2.001

**Comment by imperialjoy** [comment]
I think the problem is that SOH is not a calculated value from AHr, its actually read from the BMS directly by LeafSpy.  For example:

5B3 50 A4 FF EB C1 28 D0 8A

Right shift A4 from above, convert to base 10, and you get SOH.  Taken from (https://os.mbed.com/users/TickTock/code/CANary/rev/ef0af84a4340/)
