### ISSUE TITLE
PnP: Read Leaf max gids automatically

### ISSUE THREAD

**Issue by arsharpe** [openvehicles/Open-Vehicle-Monitoring-System-3#181]
It appears that for 30 kwh (2016 and later) Leafs the maxGids needs to be set manually using
config set xnl maxGids 356

It would make the user configuration a lot easier (ie plug-n-play) if the code could detect to the battery size (eg from available capacity or a component of the VIN number) and set the GIDs accordingly.

**Comment by caederus-ovms** [comment]
It should no longer be necessary to set xnl.maxGids to get a useful SOC reading.
The default behaviour is now to report the "instrument" SOC reading, as computed by the car internally and reported on the dash of newer models.
The older alternate method, calculating SOC as a percentage of energy in the battery relative to an arbitrary "new car" value, can be selected by: "config set xnl soc.newcar true" and "config set xnl maxGids ..." to a value of your choice.
To revert to the default behaviour: "config set xnl soc.newcar false".

**Comment by dalathegreat** [comment]
@dexterbg please close this issue, no longer relevant
