### ISSUE TITLE
AutoFlashSD should rm ovms3.done before mv ovms3.bin ovms3.done

### ISSUE THREAD

**Issue by slcasner** [openvehicles/Open-Vehicle-Monitoring-System-3#228]
If ovms3.done is still hanging around from a previous flash-from-file then the new flash-from-file will fail because ovms3.bin can't be renamed to ovms3.done.  AutoFlashSD should just rm ovms3.done first.

AutoFlashSD uses rename(2) which, on Unix at least, is supposed to handle the case where the destination already exists, but apparently this does not work in the OVMS code base.  After it failed I had no trouble manually doing rm and then mv, so it appears that the failure was not caused by access rights limitations.

Any reason not to do this?

**Comment by markwj** [comment]
Yep, rename() should delete if the destination exists. Anyway, does no harm to add a remove() first.

Implemented in 6a83c0c65fbdbd6a185ef6fc69be89b4b30767f7.
