### ISSUE TITLE
[Error] Failed to load resource: bootstrap.min.css.map

### ISSUE THREAD

**Issue by jheredianet** [openvehicles/Open-Vehicle-Monitoring-System-3#272]
I'm using the 3.2.005 version and getting this:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.css.map, line 0) http://ip/assets/bootstrap.min.css.map

**Comment by dexterbg** [comment]
https://stackoverflow.com/a/18365316
