### ISSUE TITLE
Unable to invoke factory reset 

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#276]
![Screenshot 2019-10-21 at 19 20 14](https://user-images.githubusercontent.com/758844/67231872-10e06c80-f438-11e9-8d8c-6ed0791b255d.png)

OVMS does not seem to recognise the confirmation 'Y'

**Comment by dexterbg** [comment]
Already defined as issue #82.

**Comment by glynhudson** [comment]
As a work around to enable factory reset to be invoked should the confirmation step be removed?

**Comment by dexterbg** [comment]
Yes (in terms of an additional parameter to optionally replace the confirmation). I meanwhile think very few commands may rely on a live terminal, as we also would like the commands to be usable via MSG protocol or (later) SMS.
