### ISSUE TITLE
Compatiable HUD displays? 

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#285]
What HUD displays are compatible with OVMS? Will the HUD work with any supported vehicles or just the roadster?  The only info regarding HUD's and OVMS I've found is this video:

https://www.youtube.com/watch?v=AEyjckZBgOs

I'm aware of the cable to connect a HUD being available https://www.fasttech.com/products/0/10000001/9652027-ovms-v3-hud-obd-ii-f-cable

**Comment by dexterbg** [comment]
Any OBD2 HUD will do and work with all vehicles, you just need to configure the OBD2ECU mapping as explained in the manual:
http://docs.openvehicles.com/en/latest/userguide/ecu.html

Also check the developer list archives for threads on HUD, e.g.
http://lists.openvehicles.com/pipermail/ovmsdev/2019-January/005740.html
