### ISSUE TITLE
Suddenly lost cellular connectivity 

### ISSUE THREAD

**Issue by amralomari** [openvehicles/Open-Vehicle-Monitoring-System-3#295]
Dears

Suddenly my OVMS V3.0 stopped connecting to the cellular network, tried a couple of SIMs, tried changing the modem settings, tried resetting and flashing versions of firmware and there was no solution, even tried switching antenna cables with no luck

I'm getting the signal strength (-55, -63 & -73 dbm) but not connecting

any idea why the modem not working?

**Comment by markwj** [comment]
Best to raise this as a support ticket at www.openvehicles.com. We only track bugs/enhancements here.
