### ISSUE TITLE
Tesla Roadster type incorrect for 2012 cars

### ISSUE THREAD

**Issue by einhalv** [openvehicles/Open-Vehicle-Monitoring-System-3#299]
The vehicle info in the android app reports my car with VIN *******35C3000***
to be of type 'TR1S' which presumably means Tesla Roadster 1.x Sport while the car actually is a 2.5 Sport.

The *module* code in "Open-Vehicle-Monitoring-System-3/vehicle/OVMS.V3/components/vehicle_teslaroadster/src/vehicle_teslaroadster.cpp" has some lines decoding the mid 7 bytes of the VIN and setting the variable m_type:

444  m_type[0] = 'T';
445  m_type[1] = 'R';
446  if ((d[3]=='A')||(d[3]=='B')) m_type[2] = '2'; else m_type[2] = '1';
447  if (d[1] == '3') m_type[3] = 'S'; else m_type[3] = 'N';
448  m_type[4] = 0;

Whether the vehicle is a 1.x or 2.x appears to be decided based on d[3] which holds the tenth character of the VIN. According to my understanding the tenth character codes the manufacturing year of the glider by the chassis supplier with A meaning 2010, B meaning 2011 and C meaning 2012. I therefore believe line 446 should rather read

446  if ((d[3]=='A')||(d[3]=='B')||(d[3]=='C')) m_type[2] = '2'; else m_type[2] = '1';

or something similar that sets m_type[2] = '2' also with a C in the tenth character.

**Comment by markwj** [comment]
Yep. Obvious fix. Made in 584f7620475b243dffd0ac0b87760e2bb9c7f042.
Thanks for the report.
