### ISSUE TITLE
No values reported for v.b.cac and v.b.soh

### ISSUE THREAD

**Issue by einhalv** [openvehicles/Open-Vehicle-Monitoring-System-3#300]
When I list metrics for my car, no values are reported for v.b.cac and v.b.soh. In the app values of 0 are reported.  Sensible values were reported before the recent upgrade. 
m.version is 3.2.007-93-gbd4044db/ota_1/main (build idf v3.3-beta3-774-g6652269e1 Dec  9 2019 13:47:22)
The car is a Tesla Roadster.

**Comment by einhalv** [comment]
Values are now reported after I experimented a bit with charge settings including switching from storage mode to normal and back again.

**Comment by einhalv** [comment]
Closed ny accident.

**Comment by markwj** [comment]
CAC will only be reported after a charge session completes.
