### ISSUE TITLE
TPMS message has no -1 setting for "disable" in ovms_server_v2.cpp

### ISSUE THREAD

**Issue by devmarxx** [openvehicles/Open-Vehicle-Monitoring-System-3#343]
In OVMS v2 you could make the TPMS boxes in the app invisible by setting car_stale_tpms = -1. With that setting the last number sent by the "W" message to the server was -1. This is used by the app to disable the display of the TMPS boxes.

This functionality does not longer exist in OVMS v3. It can be implemented in ovms_server_v2.cpp.

That would be of great help, because the information display in the car section will not be that crowded anymore for cars that don't support TPMS.

Thanx!

devmarxx

**Comment by markwj** [comment]
Resolved in 45968483.
