### ISSUE TITLE
Flush UART buffer when power cycling modem

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-Monitoring-System-3#354]
Thomas Heder has had some success with using uart_flush to flush the UART ring buffer when power cycling the modem. This might explain why in some cases we cannot seem to recover modem functionality by simply power cycling the modem, but resetting the OVMS module seems to recover the modem. Flushing the buffer would not seem to affect this, but perhaps something is corrupt in the ring buffer itself, so using uart_flush clears that problem.

Anyway, it does not seem to do any harm, so not a problem to add it and see if it improves the situation.

**Comment by leres** [comment]
That would be awesome if it fixed it.

**Comment by markwj** [comment]
Change applied in 9de2ecd9.
