### ISSUE TITLE
Wifi powersave - how to reactivate after turned off?

### ISSUE THREAD

**Issue by ltjessem** [openvehicles/Open-Vehicle-Monitoring-System-3#367]
I've activated power saving to turn wifi off after 1 hour, how do I reactivate it when needed?
`power wifi on` claims to turn on the power but doesn't work.

**Comment by dexterbg** [comment]
I think I've fixed that todo in commit d8028d5d3fa1792823ac349211d0fb82055c1ec0, so closing this.
