### ISSUE TITLE
Persistent metrics get lost over firmware update

### ISSUE THREAD

**Issue by dexterbg** [openvehicles/Open-Vehicle-Monitoring-System-3#380]
Subject says all. An OTA update resets all persistent values.

@leres 
Maybe it's sufficient to explicitly rewrite the RTC storage after the flash process?

**Comment by leres** [comment]
I still don't understand what you mean when you say, "persistent metrics get lost." Do they get zero'ed or are they garbage? What does "metrics list -p" look like when metrics are lost?

You can tell if pmetrics were zero'ed on bootup by looking at the serial number in the log message:
```
  /* Persistent metrics initialization */
  if (pmetrics.magic != PERSISTENT_METRICS_MAGIC ||
    pmetrics.version != PERSISTENT_VERSION ||
    pmetrics.size != sizeof(pmetrics))
    {
    memset(&pmetrics, 0, sizeof(pmetrics));
    pmetrics.magic = PERSISTENT_METRICS_MAGIC;
    pmetrics.version = PERSISTENT_VERSION;
    pmetrics.size = sizeof(persistent_metrics);
    }
  ESP_LOGI(TAG, "Persistent metrics serial %u using %d bytes",
      pmetrics.serial++, sizeof(pmetrics));
```
If the serial number is 1, then pmetrics was zero'ed as part of this boot. You can also tell if "metrics persist" reports the serial number is 1.

I could add a log that details when and why it is reset.

> I assume it's a side effect (bug) of the flash process. I also have seen corrupted data in the ovms_boot data after an OTA update, the boot struct doesn't have any checksum/magic word to check for corruption yet.
>
> That's why I think it's worth trying to simply rewrite all persistent metrics after the flash process.

By rewrite do you mean zero? I'd really like to avoid this, in my mind it's the whole reason for the feature. (I'm pretty sure I don't understand the problem yet.)

I thought about adding a magic number at the very end of the pmetrics struct. I could also just add a checksum. 

> I also update my module using the flash from web tab, and it has erased the persistent data on the last two updates, which already included your code. Regarding this, the persistent metrics feature has been released to the OTA edge branch as soon as it was merged (nightly builds). Maybe your OTA is configured for the main branch?

One of the updates would have included a change to the pmetrics array size; that would have triggered zero'ing the pmetrics struct.

I have "Enable auto update" disabled everywhere and have only been using my own builds. Is "Flash from web" an OTA update or does it have to be automatic?

I just flashed my dev unit with 3.2.013-43-g6e498a1 from here:

`http://api.openvehicles.com/firmware/ota/v3.1/edge/ovms3.bin`

No loss of pmetrics. I flashed it back and it's still ok.

**Comment by dexterbg** [comment]
The effect was that all metrics were cleared, although the metrics structure had not been changed on that specific update. That's why I assumed some RTC data corruption triggered your consistency check. Log isn't available as it happened on my car module, and the boot log doesn't get written to the log file.

Good news is it doesn't happen everytime. I cannot reproduce it now, did multiple OTA flashes in series without data loss. The boot data corruption also only occurs by chance -- you can tell it happened if your boot status shows something like "This is reset #1073667054 since last power cycle".

By rewrite I mean rewrite, not zero. I.e. loop over all persistent metrics and do `*m_valuep = m_value`.

**Comment by dexterbg** [comment]
> I have "Enable auto update" disabled everywhere and have only been using my own builds. Is "Flash from web" an OTA update or does it have to be automatic?

I flash my own builds manually directly from my local server. "Flash from web" is the same OTA update procedure as the automatic version, just triggered manually.

**Comment by leres** [comment]
I just opened a pull request to track and report the reason persistent metrics were reset. You can see it after boot using:
```
metrics persist
version 1, serial 1, magic caused reset this boot, 420 bytes, and 20 of 20 slots used
```
> By rewrite I mean rewrite, not zero. I.e. loop over all persistent metrics and do *m_valuep = m_value.

That already happens. Here's the end of OvmsMetricFloat::OvmsMetricFloat():
```
  m_valuep = &vp->value;
  m_value = *m_valuep;
  if (m_value != 0.0)
    SetModified(true);
  ESP_LOGI(TAG, "persist %s = %s", name, AsUnitString("?", units).c_str());
```
On boot, the "new OvmsMetricFloat()" calls find the metric and assign the correct address to m_valuep.

**Comment by dexterbg** [comment]
Your code quote is the initial read (`m_value = *m_valuep`). I meant adding a full writeback (`*m_valuep = m_value`) either after the OTA update, or generally hooked into the shutdown sequence.

**Comment by dexterbg** [comment]
OK, that would only help if just the values get trashed. Better rewrite the whole persistent storage structure.

**Comment by leres** [comment]
> Your code quote is the initial read (m_value = *m_valuep). I meant adding a full writeback (*m_valuep = m_value) either after the OTA update, or generally hooked into the shutdown sequence.

The OvmsMetricInt::SetValue() methods are doing the (*m_valuep = m_value). Is the issue memory corruption of the pmetrics struct during a OTA update?

It would be easy to add a checksum; I see crc32() are available in zlib. The crc would be updated on write and could be checked at startup and shutdown. This approach has the downside of doing a lot of RTC reads on every persistent metric change.

We could also calculate checksums just before and after an OTA update and complain/rewrite if they differ.

> OK, that would only help if just the values get trashed. Better rewrite the whole persistent storage structure.

My thought is rather than unconditionally doing a (*m_valuep = m_value) at shutdown I would want to check for discrepancies and report/rewrite any that are found.

**Comment by dexterbg** [comment]
See my second comment above: yes, I assume the issue is RTC memory corruption during the OTA update, as I have seen the very same effect on the boot RTC data.

Meanwhile I've added a CRC check to the boot data, see commit https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/commit/ce3be4725a8fee649266353fe4143e807b6e341d
I used the IDF ROM version of the crc32 calculation (no dependancy on the optional zip component).

Just checking for a corruption won't help, the data will still be lost. That's ok for the boot data, but should be last resort for the metrics. A simple full rewrite of the pmetrics struct should be sufficient.

**Comment by leres** [comment]
Ok I think I've finally caught up with you. Here's a [pull request](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/390) that checks the pmetrics struct on shutdown and if it finds any problems it recreates it from scratch.

**Comment by dexterbg** [comment]
I haven't seen the effect since, so assuming solved.
