### ISSUE TITLE
hope add sae j1939 protocol and tensorflow lite for AI application

### ISSUE THREAD

**Issue by xiangxud** [openvehicles/Open-Vehicle-Monitoring-System-3#385]
II want to add SAEJ1939 protocol support and tensorflow Lite framework. How can I start？

**Comment by dexterbg** [comment]
Welcome :-)

Please introduce yourself on the developer mailing list:

- http://lists.openvehicles.com/mailman/listinfo/ovmsdev

The general basic developer documentation is here:

- https://docs.google.com/document/d/1q5M9Lb5jzQhJzPMnkMKwy4Es5YK12ACQejX_NWEixr0/edit

It may be outdated in some aspects but should get you started. Post questions on the developer mailing list.

Have a look at the components directory for typical component integration style. If the component will be a fork of some existing git repository, add it as a git submodule (examples: mongoose, libzip) rooted in a dedicates subdirectory. If you need to make modifications for the ESP32 environment, the modified fork should be added to the openvehicles account and the submodule will then point to that repository. That way the ESP32 modified library can also be used for other ESP32 projects.

Try to keep the OVMS system integration layer as separate as possible from the underlying external lib / implementation. For a protocol integration like SAE J1939, I suggest adding a dedicated protocol service task and shell command interface. Protocol operation requests can then be sent from any other task to the service, which takes care of handling the communication and returns overall results to the callers. For an example of how this can be done, have a look at the CANopen component:

- https://docs.openvehicles.com/en/latest/components/canopen/docs/Commands.html
- https://docs.openvehicles.com/en/latest/components/canopen/docs/API.html

Regards,
Michael
