### ISSUE TITLE
Wifi Config Enhancement

### ISSUE THREAD

**Issue by drc38** [openvehicles/Open-Vehicle-Monitoring-System-3#386]
I'm looking to use Ovms via wifi only, with wifi going between two home networks and mobile hotspot plus potentially others. The current framework appears to be quite limited in terms of setting wifi client defaults and handling switching of networks when signal is lost. 

Often ovms will report good wifi signal but show no ip/dns/gateway etc in the status panel.

Would it be possible to extend management options/config by including a wifi manager such as esp32-wifi-manager in the build?

**Comment by dexterbg** [comment]
Yes, that would be possible. Or you could simply add the functionality you're missing to the OVMS wifi manager.
