### ISSUE TITLE
esp-idf tools error

### ISSUE THREAD

**Issue by superxxd** [openvehicles/Open-Vehicle-Monitoring-System-3#407]
anyone know how to config tools' environment

According to development manual install my tools environment
I re-install ncurses-devel,the problem remains
$ pacman -S ncurses-devel

 
$ make menuconfig
make[1]: 进入目录“/C/ovms/msys64/home/xiang/esp-idf/tools/kconfig”
/C/ovms/msys64/home/xiang/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh -check /usr/bin/gcc -D_XOPEN_SOURCE=600 -D_POSIX_C_SOURCE=199506L -I/mingw32/include/ncursesw -I/mingw32/include -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP -pipe -lncursesw -lgnurx -ltre -lintl -liconv -lintl
 *** Unable to find the ncurses libraries or the
 *** required header files.
 *** 'make menuconfig' requires the ncurses libraries.
 ***
 *** Install ncurses (ncurses-devel) and try again.
 ***
make[1]: *** [Makefile:217：dochecklxdialog] 错误 1
make[1]: 离开目录“/C/ovms/msys64/home/xiang/esp-idf/tools/kconfig”
make: *** 没有规则可制作目标“/C/ovms/msys64/home/xiang/esp-idf/tools/kconfig/conf-idf”，由“/C/ovms/msys64/home/xiang/esp-idf/tools/kconfig/mconf-idf” 需求。 停止。

**Comment by dexterbg** [comment]
Closing as this isn't related to the OVMS code.
Please ask for help on the developer list or at Espressif if you still have this problem.
