### ISSUE TITLE
Support for TLS updates

### ISSUE THREAD

**Issue by chrisstaite** [openvehicles/Open-Vehicle-Monitoring-System-3#449]
It would be fairly simple to intercept the OTA requests to the update server and push bad firmware to all OVMS devices. In addition, with encryption as standard it's hard to disable it.

**Comment by chrisstaite** [comment]
Solved by changes to the OTA in v3.3

**Comment by leres** [comment]
Is this really solved? I have 3.2.016-55-g2edf7398 running and if I use "Flash from web" with and https url I get "Error: Request failed"

**Comment by chrisstaite** [comment]
It's solved in v3.3 as stated.
