### ISSUE TITLE
Idle alert while charging

### ISSUE THREAD

**Issue by chrisstaite** [openvehicles/Open-Vehicle-Monitoring-System-3#453]
While the car is charging, in order to get charge status for the MG it is required to be kept awake.  The check in vehicle.cpp that does an idle alert is as follows:

`if (!StdMetrics.ms_v_env_awake->AsBool() || StdMetrics.ms_v_pos_speed->AsFloat() > 0)`

Therefore an alert is sent because it is awake but not moving but that's because it is charging.  I wonder whether adding to the check that it is not charging would be beneficial.  Or is this an edge case for the MG that should be handled by the vehicle component?

**Comment by dexterbg** [comment]
Clearly a case you need to handle by overriding `OvmsVehicle::NotifyVehicleIdling()`, as the alert is also meant to notify the driver about the car being left switched on while charging, which is a crucial alert for some vehicles.

Side note: this isn't an issue, the developer mailing list is meant to ask & discuss general questions like this.
