### ISSUE TITLE
OVMSDEV mailing list - is it still functioning?

### ISSUE THREAD

**Issue by elbow** [openvehicles/Open-Vehicle-Monitoring-System-3#467]
Hi,

I apologise for opening an issue - but I’m trying to get subscribed to the ovmsdev mailing list.

Is there a technical problem - or has development discussion gone somewhere else?

I've sent two subscription requests for the ovmsdev mailing list via the interface at http://lists.openvehicles.com/mailman/listinfo/ovmsdev

I subscribed steve+ovmsdev@telviva.co.za - an address that comes to me.

I also sent from steve@telviva.co.za my “plain” address.

I didn't receive a confirmation or any other reply.

I wrote a followup email to ovmsdev-owner@lists.openvehicles.com but haven’t had a reply.  Or I should say I didn’t receive a reply.

Can someone help?

Thanks!

**Comment by elbow** [comment]
Seems like the last message was about some migration Sep 18 - nothing after.

Is the list server broken - where can I find development discussion?

**Comment by dexterbg** [comment]
Last message was four days ago about the PSRAM fix… you're right, the list archive seems to be broken since migration to the new server → @markwj Mark, please have a look.

**Comment by elbow** [comment]
thanks - subscribing seems to be broken too

**Comment by elbow** [comment]
Hi @dexterbg @markwj ,

The situation with the list is unchanged.  I also received bounces from my mails to lists.openvehicles.com:

`This is the mail system at host nbkfmailscanhq5.network-box.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

< ovmsdev-owner@lists.openvehicles.com>: connect to 10.8.12.188[10.8.12.188]:25:
    Connection refused
`

So the mx targets for lists.openvehicles.com are "network-box.com" machines.  Apparently they can't forward to mail on?

For me I just want to be added to the dev mailing list.  Can it be done by hand?

I'm making good progress reverse engineering I3 canbus pids.

**Comment by dexterbg** [comment]
I'm now also having problems sending mail to the list as well as to Mark directly:

```
<ovmsdev@lists.openvehicles.com>: host mailtp5.network-box.com[175.45.17.210]
    said: 554 command rejected for policy reasons (using messageid:
    4a4bb48c-28d7-11eb-a59c-7e589b37a1b9) (in reply to end of DATA command)
```

My mail server is on no block list, so this looks like a local issue.
Or maybe Mark is working on the issue already.

@slcasner Steve, can you try to reach Mark?

**Comment by markwj** [comment]
Sorry for the delay in replying. I've been unwell since the weekend (3am visit to hospital emergency room was not fun - particularly in times of COVID-19). Nothing serious, and recovering now.

Michael and Steve escalated this to me, and I found both the postfix and mailman services not running. I have restarted both, and they seem to be working ok now. Can you try to sign-up again? If it still doesn't work, let me have the eMail address that you want to use and I will manually add you.

**Comment by elbow** [comment]
Hi Mark,

Thanks for coming back to me and get well soon.

Steve


-- 
Steve Davies: Chief Technical Officer, Telviva (Pty) Ltd
(formerly Connection Telecom (Pty) Ltd)
Phone: 0878200262 / 0878200200

**Comment by elbow** [comment]
Hi @markwj 

I did attempt again to subscribe to the list via the mailman interface but I didn't see a subscription confirmation email or any posts.

Perhaps you can just add steve@telviva.co.za for me.

Thanks,
Steve

**Comment by elbow** [comment]
Hi @markwj, et al,

I just sent another subscription request via the mailman interface and I'm happy to say that I received the confirmation.

I'm now waiting moderator approval that I may join - so I'd appreciate being approved.

Thanks,
Steve

**Comment by elbow** [comment]
Hi team,

Could a ovmsdev list moderator please approve my join to the mailing list.

Thanks,
Steve

**Comment by markwj** [comment]
Steve,

Your membership was approved a couple of days ago. It looks ok at the moment. Can you try to send an introduction message to the list?

**Comment by elbow** [comment]
resolved (except apparently my messages to the list are getting duplicated...?)

**Comment by dexterbg** [comment]
@markwj Hoping this gets through to you, the new mail server is blocking me again:

```
The mail system
<ovmsdev@lists.openvehicles.com>: host mailtp5.network-box.com[175.45.17.210]
    said: 554 command rejected for policy reasons (using messageid:
    0ce20a9a-3ddd-11eb-b114-7e589b37a1b9) (in reply to end of DATA command)
```

My mail server is on no blacklist, and the message contained no offensive parts or attachments.
Could you please consider changing the policy violation thresholds?

Regards,
Michael

**Comment by markwj** [comment]
Issue was an ‘iframe’ embedded in the html. I have released it, and added you to the whitelist.

Regards, Mark.

**Comment by dexterbg** [comment]
Thanks Mark, but my mail client did not add that iframe, it just was in the quote. The iframe apparently was added by your mail client on your response to the APNS thread.

**Comment by markwj** [comment]
Confused, as I can’t find any such reply. I use Mac mail, and don’t see it adding or iframe embedding anything. Perhaps done at GitHub? Anyway, I’ve added the ’noreply’ address from GitHub so this shouldn’t block (for this reason) any more.

Regards, Mark.

**Comment by dexterbg** [comment]
No, I mean in your reply to the mailing list today. From your email source:
```
class=3D""></div></div><br class=3D""><iframe =
class=3D"content-isolator__isolated-content" sandbox=3D"allow-scripts" =
scrolling=3D"auto" width=3D"200" height=3D"10" =
style=3D"border:none;display:block;overflow:auto;" =
data-src=3D"data:text/html;charset=3DUTF-8;base64,PGlmcmFtZS1jb250ZW50IGRh=
dGEtaWZyYW1lLWhlaWdodD0idHJ1ZSI+X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1=
9fX19fX19fX19fX19fX188QlI+T3Ztc0RldiBtYWlsaW5nIGxpc3Q8QlI+T3Ztc0RldkBsaXN0=
cy5vcGVudmVoaWNsZXMuY29tPEJSPmh0dHA6Ly9saXN0cy5vcGVudmVoaWNsZXMuY29tL21haW=
xtYW4vbGlzdGluZm8vb3Ztc2RldjxCUj48L2lmcmFtZS1jb250ZW50Pg=3D=3D"></iframe><=
```

This has been added by your client, it wasn't in my original post.

**Comment by markwj** [comment]
The message I received from the list is attached. It contains this at the bottom:

class=3D"protected-content">Mark,<br class=3D""><br class=3D"">a user =
informed me he no longer gets any push notifications to iOS.<br =
class=3D""><br class=3D"">Looking into the logs, it seems the initial =
connect to the gateway fails in a way the perl code does not handle.<br =
class=3D""><br class=3D"">I've found this in the Apple forums: <a =
href=3D"https://developer.apple.com/forums/thread/667248" =
class=3D"">https://developer.apple.com/forums/thread/667248</a><br =
class=3D""><br class=3D"">It seems the protocol we use has been =
deprecated, but it should continue to work until March. Do you see a =
similar effect on your server?<br class=3D""><br class=3D"">Regards,<br =
class=3D"">Michael<br class=3D""><br class=3D"">-- <br class=3D"">Michael =
Balzer * Helkenberger Weg 9 * D-58256 Ennepetal<br class=3D"">Fon 02333 =
/ 833 5735 * Handy 0176 / 206 989 26<br class=3D""><br class=3D""><br =
class=3D""></div></div><br class=3D""><iframe =
class=3D"content-isolator__isolated-content" sandbox=3D"allow-scripts" =
scrolling=3D"auto" width=3D"200" height=3D"10" =
style=3D"border:none;display:block;overflow:auto;" =
data-src=3D"data:text/html;charset=3DUTF-8;base64,PGlmcmFtZS1jb250ZW50IGRh=
dGEtaWZyYW1lLWhlaWdodD0idHJ1ZSI+X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX1=
9fX19fX19fX19fX19fX188QlI+T3Ztc0RldiBtYWlsaW5nIGxpc3Q8QlI+T3Ztc0RldkBsaXN0=
cy5vcGVudmVoaWNsZXMuY29tPEJSPmh0dHA6Ly9saXN0cy5vcGVudmVoaWNsZXMuY29tL21haW=
xtYW4vbGlzdGluZm8vb3Ztc2RldjxCUj48L2lmcmFtZS1jb250ZW50Pg=3D=3D"></iframe><=
/div></div></div></blockquote></div><br =
class=3D""></div></div></body></html>=

Regards, Mark

**Comment by dexterbg** [comment]
That has been added by your mail client. I've attached a ZIP with both my initial post and your reply, as I got them from the list.

[mails.zip](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/files/5687406/mails.zip)

**Comment by markwj** [comment]
I am wondering if this is the mailman doing this? I see the iframe isolated content is:

PGlmcmFtZS1jb250ZW50IGRhdGEtaWZyYW1lLWhlaWdodD0idHJ1ZSI+X19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX188QlI+T3Ztc0RldiBtYWlsaW5nIGxpc3Q8QlI+T3Ztc0RldkBsaXN0cy5vcGVudmVoaWNsZXMuY29tPEJSPmh0dHA6Ly9saXN0cy5vcGVudmVoaWNsZXMuY29tL21haWxtYW4vbGlzdGluZm8vb3Ztc2RldjxCUj48L2lmcmFtZS1jb250ZW50Pg==

That base64 decodes to:

<iframe-content data-iframe-height="true">_______________________________________________<BR>OvmsDev mailing list<BR>OvmsDev@lists.openvehicles.com<BR>http://lists.openvehicles.com/mailman/listinfo/ovmsdev<BR></iframe-content>

That seems to be the standard mailman footer.

I will keep looking. At least the list archives have the messages so I can try to trace where they are coming from.

Regards, Mark.
