### ISSUE TITLE
ABRP plugin: does not initialise correctly after crash/boot while vehicle running

### ISSUE THREAD

**Issue by ethan4** [openvehicles/Open-Vehicle-Monitoring-System-3#470]
While on a long drive I noticed the module crashing frequently while using the ABRP plugin, however it never seemed to start the updates again which I believe is due to not seeing the vehicle on state change.

**Comment by dexterbg** [comment]
Closing this. The ABRP plugin is now maintained by Jason at Iternio: https://github.com/iternio/ovms-link

If you're having issues with the current release, open an issue there.
