### ISSUE TITLE
incorrectly shows as "Not Charging" when it is charging (i-MiEV)

### ISSUE THREAD

**Issue by jjlink** [openvehicles/Open-Vehicle-Monitoring-System-3#473]
I verified the SOC is going up so the vehicle is charging; however both the web page and the Android app indicate its not charging most of the time. Using the web interface it did show charging earlier today, so its seems to be sporadic. I monitored it using MQTT explorer and it showed charging at that same time when the web interface showed charging.

**Comment by jjlink** [comment]
These MQTT records are from earlier today when it was working:
ovms/jjlink/OVMS-PLUGNEV2/notify/info/charge.started
 - Charging
0.0V/0.0A
SOC: 88.5%
Ideal range: 49km
Est. range: 38km
ODO: 101856.0km
CAC: 27.5Ah
SOH: 57%
AC charge: 0.001kWh kWh
DC charge: 0.001kWh kWh
 - Charging
0.0V/0.0A
SOC: 88.5%
Ideal range: 49km
Est. range: 38km
ODO: 101856.0km
CAC: 27.5Ah
SOH: 57%
AC charge: 0.001kWh kWh
DC charge: 0.001kWh kWh

ovms/jjlink/OVMS-PLUGNEV2/notify/alert/charge.stopped
Not charging
SOC: 90.0%
Ideal range: 50km
Est. range: 39km
ODO: 101856.0km
CAC: 27.5Ah
SOH: 57%
AC charge: 0.194kWh kWh
DC charge: 0.111kWh kWh

**Comment by KommyKT** [comment]
Hi jjlink!
Please,  try this version of fw: kommykt-nas.ddns.net:22289/dev/test/ovms3.bin 
I modified a bit the "charging detection"
This is a public charger or a home charger?

**Comment by jjlink** [comment]
This is a home charger (OpenEVSE). That seems to have got it working again. Thanks!

Type1 - Charging
253.0V/5.9A
SOC: 78.5%
Ideal range: 44km
Est. range: 34km
ODO: 101861.0km
CAC: 27.5Ah
SOH: 57%
AC charge: 0.001kWh kWh
DC charge: 0.000kWh kWh

**Comment by jjlink** [comment]
The BMS cell monitor page is blank. 

Also the am getting a bunch of these alerts:
Voltage: SD=7mV OK
Temperature: SD=1.4C !47:+3.1C

**Comment by jjlink** [comment]
I just tried charging again and now it not working, so its only works sometimes.

Not charging
SOC: 82.0%
Ideal range: 46km
Est. range: 35km
ODO: 101861.0km
CAC: 27.5Ah
SOH: 57%
AC charge: 0.427kWh kWh
DC charge: 0.282kWh kWh

**Comment by KommyKT** [comment]
I have a 2012 Peugeot iON and OpenEVSE. But I have no problem with charge detection, only problem the previous version if crash the module while charging not showing the type of charging, now this is fixed.
Next charge please, send the following output result, if show the charging and if not: 
me li v.c
me li xmi.c

**Comment by jjlink** [comment]
This time it shows charging..

I will try it again later and see if it works a second time (last time it didn't).

![OVMS-MQTT](https://user-images.githubusercontent.com/6171474/100660184-8343a180-3306-11eb-99a0-01c2126a6e9e.jpg)

The web interface:
[OVMS Status.pdf](https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/files/5618504/OVMS.Status.pdf)

![OVMS_app](https://user-images.githubusercontent.com/6171474/100660473-ee8d7380-3306-11eb-957c-56201684e406.jpg)

OpenEVSE:
![Open_EVSE](https://user-images.githubusercontent.com/6171474/100660789-5cd23600-3307-11eb-8278-206af6a38e4a.jpg)

**Comment by jjlink** [comment]
Ok, a little later after I stopped the previous session for like a half hour or so and then started it again. Now this time it says not charging:
![Not_charging](https://user-images.githubusercontent.com/6171474/100663311-f3ecbd00-330a-11eb-9fc3-813ad01392f9.jpg)
![1](https://user-images.githubusercontent.com/6171474/100663326-f818da80-330a-11eb-9247-3da2b06011bb.jpg)
![2](https://user-images.githubusercontent.com/6171474/100663340-fc44f800-330a-11eb-8385-0a3501a4dcef.jpg)
![3](https://user-images.githubusercontent.com/6171474/100663353-02d36f80-330b-11eb-9b2d-036ef5d3c994.jpg)

**Comment by KommyKT** [comment]
- The BMS cell monitor page is blank.
     - Please go to TRIO / Settings and  hit Save button, then start the car, I think this fix this.
- Also the am getting a bunch of these alerts:
   Voltage: SD=7mV OK
   Temperature: SD=1.4C !47:+3.1C
     -  You can edit notifications in BMS Cell page in Alert Config

For charge detection OVMS use the 286 pid, please set up [retools plugin ](https://docs.openvehicles.com/en/latest/plugin/retools/README.html)
and start it and in search type 286, and send a screenshot if charge not detected

**Comment by KommyKT** [comment]
Nothing?
Really hard to help, if I can not get data, because my car charge sensing is works 100%. Now I fix some small bug.
Now I changed the test version to my last version: kommykt-nas.ddns.net:22289/dev/test/ovms3.bin

**Comment by jjlink** [comment]
Yes, I am looking at setting up the re tool plugin right now. Thanks

**Comment by jjlink** [comment]
I have the retool running. I did a capture while doing a brief charge. It did say charging as usual the on the first try.
How do I see the detail records for a single PID (like 286)? I don't see the instructions in the developer docs.
![charge-1](https://user-images.githubusercontent.com/6171474/102818282-29268100-4386-11eb-94cf-c4a0e538ecf1.jpg)

**Comment by KommyKT** [comment]
Please create a log file with charge detected, and one without detect, if you can.
I think the simplest method create a folder on SD card with Tools/Editor named "logs"
then Tools/Shell and type:
can log start vfs crtd /sd/logs/charge.csv 
This create a log file to sd card logs folder with charge.csv name run about 1-2 minutes then type the following command:
can log stop
Now open another tab and open: ip_of_ovms/logs
and download the charge.csv file, and send for my


my email is my name and gmail.com

**Comment by jjlink** [comment]
I just tried doing a charging log and OVMS crashed in the middle of it. So I got no log file. I will try again...

**Comment by jjlink** [comment]
Seems to be working now.
