### ISSUE TITLE
Web login is not secure

### ISSUE THREAD

**Issue by slcasner** [openvehicles/Open-Vehicle-Monitoring-System-3#48]
The web login is not secure, so in Safari the nav bar changes to "Website not secure" when the focus goes to the username field.  This is really not good enough for users.  What is needed to support https?

**Comment by dexterbg** [comment]
Installing a certificate to enable https is now supported, but you still won't get any browser to accept a self-signed certificate as a "secure site".

**Comment by leres** [comment]
> Installing a certificate to enable https is now supported, but you still won't get any browser to accept a self-signed certificate as a "secure site".

What if you install the self-signed root CA in the browser?

**Comment by dexterbg** [comment]
That should also work. Try and report.

**Comment by leres** [comment]
> That should also work. Try and report.

It works!

**Comment by slcasner** [comment]
Works for me, too.  Should our webserver implement redirect from http to https if a cert and key are installed?

**Comment by dexterbg** [comment]
No, or at most optionally, and if so probably only for the main UI (web app). HTTPS has a much higher connect overhead so would introduce some seconds additional load time for all scripts calling the REST API or fetching files.
