### ISSUE TITLE
[REQ] Pre-OBD support

### ISSUE THREAD

**Issue by Gouster4** [openvehicles/Open-Vehicle-Monitoring-System-3#616]
Hi. Can you support Pre-OBD vehicles?
Like by connecting All sensors and stuff to some module. That way even on obd compatible vehicles u Can avhieve aditional functions that are not supported by ecu by connecting aditional sensors or electronics.

**Comment by dexterbg** [comment]
Yes.

See:
- https://docs.openvehicles.com/en/latest/userguide/egpio.html
- https://docs.openvehicles.com/en/latest/introduction.html#extensions
- https://docs.openvehicles.com/en/latest/userguide/kline.html
- https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/tree/master/vehicle/hardware
