### ISSUE TITLE
ABRP plugin crashing?

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#643]
The ABRP (A better router planner) OVMS plug-in works great but crashes after about 15min-20min which makes it unusable for long trips. Has anyone else experienced this? Any idea what I can do to try and debug?

**Comment by dexterbg** [comment]
Glyn, did you notice Jason has published his rework of the plugin at iternio?

- https://www.openvehicles.com/node/2831
- https://github.com/iternio/ovms-link

**Comment by glynhudson** [comment]
Thanks, I can confirm V1.4 ABRP plugin available from https://github.com/iternio/ovms-link works well, crashing issues seems to be fixed 👍 

I'll make a PR to update the OVMS ABRP docs to reference iternio/ovms-link repo
