### ISSUE TITLE
NL: HVAC metrics incorrect for MY2013

### ISSUE THREAD

**Issue by mjkapkan** [openvehicles/Open-Vehicle-Monitoring-System-3#644]
It looks like the HVAC gets set to yes every time the car is charging. This was already fixed in #281, but it looks like something broke it afterwards.

**Comment by glynhudson** [comment]
I''ve also noticed this issue

**Comment by drc38** [comment]
The only functional difference I can spot is the code for the fan speed. 
```
int fanspeed_int = ((d[4] & 0x38) >> 3); //use bits 5:3 to read fan speed
m_climate_fan_speed->SetValue(fanspeed_int / 7.0 * 100);
```
versus
```
int fanspeed_int = d[4] / 8;
// todo: actually we need to use individual bits (7:3) here as remaining ones are for something else
if ((fanspeed_int < 1) || (fanspeed_int > 7))
      {
        fanspeed_int = 0;
      }

m_climate_fan_speed->SetValue(fanspeed_int);
```
is the fan speed also showing as >0 when charging?

**Comment by drc38** [comment]
Also in https://github.com/openvehicles/Open-Vehicle-Monitoring-System-3/pull/376/files on line 752 should it be a bitwise & or logical &&?
`hvac_calculated = (climate_on & (m_climate_fan_speed->AsInt() != 0));`

**Comment by mjkapkan** [comment]
Yeah, I now remember that CC flag used to be on during charging so I added the fan speed as an additional check (you can never have hvac on if the fan is not running). So this one needs to be logical. I will test how it looks tonight.

**Comment by mjkapkan** [comment]
Checked. So it seems whenever the car is charging we get 57% of fanspeed. We could use this rule+xnl.cc.fanonly metric to mitigate this until we find another solution.

**Comment by dalathegreat** [comment]
I checked this yesterday on my 2015 LEAF running the latest build, fanspeed was at 0%, so no issue here?

**Comment by mjkapkan** [comment]
@dalathegreat Checked just now. Issue still persists. If vehicle is charging, then fanspeed is set to 14%, and hence CC flag is enabled. If you dont't have this issue, then it could be limited to <2015 MY cars.

**Comment by mjkapkan** [comment]
Basically this should be an easy fix. We just need yo find one more metric to validate against.

**Comment by mjkapkan** [comment]
Implemented a hacky fix, le't see if it works for most and then we can close it. Link to beta firmware in PR: #676 .

**Comment by mjkapkan** [comment]
Permanent fix implemented. PR #676 should close this issue.

**Comment by drc38** [comment]
The changes look useful. The substate transitions may need some tweaking however. Plugging in to my charger which does not charge until a set time of day no longer transitions out of a powerwait substate. 
![Screenshot_20220107-210126_Open Vehicle](https://user-images.githubusercontent.com/20024196/148512297-a3b93468-3507-41cc-978d-da6e42597f79.jpg)
