### ISSUE TITLE
Twizy changing voltage limit

### ISSUE THREAD

**Issue by Kamsta99** [openvehicles/Open-Vehicle-Monitoring-System-3#646]
Source: https://github.com/dexterbg/Twizy-Virtual-BMS/blob/master/extras/SEVCON-Configuration.md
![obraz](https://user-images.githubusercontent.com/8656801/128094876-7d26e063-7e00-4f62-888e-8d35d878b0bf.png)
I tried doing this via Ovms, no success still cutsoff after 39 V

Patient:
Twizy, 2012 ,custom 8.7 kwh battery,

What i tried already:
Setting Twizy same as for applying tuning (no switching to GO)
In shell:
1. enable <pass>
2. xrt cfg pre
3. xrt cfg write 2c02 01 592
4. xrt cfg write 2c02 02 560
5. says --> OK, value edited is same as we set
6. But still cutsoff, with STOP light and SEVCON low voltage error

**Comment by dexterbg** [comment]
Crossposting, also unrelated to OVMS → closing.
