### ISSUE TITLE
Trying to update: "Error: Download file size does not match expected" 

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#654]
I'm trying to update from `3.2.015` to `3.2.17`, using `api.openvehicles.com/firmware/ota`, I've been getting error message `Download file size does not match expected`. Any idea going wrong? 

![Screenshot from 2021-10-05 00-14-30](https://user-images.githubusercontent.com/758844/135937360-059eef15-7b63-48e0-989e-a3a5276a99fd.png)

I've also tried to update from `dexters-web.de/firmware/ota/v3.3/edge/ovms3.bin`, however I get error
`Error: ESP32 error #5379 when writing to flash - state is inconsistent`

**Comment by dexterbg** [comment]
Glyn,

these are different errors (first is an aborted download, second some issue while flashing) but may be caused by a general issue with that module's configuration. Try flashing from SD card, release 3.2.017 possibly solves the issue for the next OTA update.

Regards,
Michael
