### ISSUE TITLE
HTTP API send commands?

### ISSUE THREAD

**Issue by glynhudson** [openvehicles/Open-Vehicle-Monitoring-System-3#655]
Is it possible to use the [HTTP API](https://docs.openvehicles.com/en/latest/protocol_httpapi/index.html) to send msg commands to the OVMS module, e.g to trigger a custom ABRP script?

**Comment by dexterbg** [comment]
If using the module's web interface is an option, creating a plugin adding trigger buttons to e.g. the main menu or dashboard is pretty simple.

Adding buttons to start & stop the ABRP transmission on the dashboard would for example basically just need this: add a hook type plugin for page `/dashboard` hook `body.pre` containing…

```
<div id="abrp-control" style="display:none">
  <button type="button" class="btn btn-info" data-target="#abrp-out" data-js="abrp.send(1)">ABRP ON</button>
  <button type="button" class="btn btn-info" data-target="#abrp-out" data-js="abrp.send(0)">ABRP OFF</button>
  <samp class="samp-inline" id="abrp-out" />
</div>

<script>
  $('#main').one('load', function(ev) {
    $('#abrp-control').appendTo('#panel-dashboard .panel-body').show();
  });
</script>
```

If using the Android App, a command can be triggered using a `SendCommand` broadcast (see https://github.com/openvehicles/Open-Vehicle-Android/wiki/SendCommand-Broadcast-Intent-data).

Just use some automation App like Automagic or Tasker, add a widget/button/whatever to trigger sending a broadcast with your vehicle credentials and `msg_command` set to e.g. `7,script eval abrp.send(1)` to start the ABRP transmission. Don't forget to configure the App to allow command intents.

Regards,
Michael
