### ISSUE TITLE
4G/5G modem module? (mobile networks that are planning to retire 2G and 3G)

### ISSUE THREAD

**Issue by zymurgic** [openvehicles/Open-Vehicle-Monitoring-System-3#658]
In various countries there are plans afoot to switch off GSM 2G and 3G mobile networks. Many have already turned off 2G.
Given that a lot of vehicles were made with factory-fit telemetry that was 2G-only, then when 2G gets retired, there will be a market for OVMS replacing the factory-fit telemetry units, for better functionality, however if the mobile networks are retire their 3G coverage the following year, then it would be better future-proofing to see if there's a drop-in modem module that supports the newer mobile networking standards, that can be fitted to new hardware builds.

**Comment by dexterbg** [comment]
- https://dexters-web.de/ovms-v3.3-certification-passed-text_100.en.htm
- https://www.openvehicles.com/comment/7858#comment-7858
