### ISSUE TITLE
Nissan Leaf: charge start not working

### ISSUE THREAD

**Issue by drc38** [openvehicles/Open-Vehicle-Monitoring-System-3#691]
@dalathegreat @mjkapkan on my 2016 I get the following notification when trying to start charging after it has been in the `SuspendedEV` state. Do you get the same issue?

![image](https://user-images.githubusercontent.com/20024196/151693612-27cbe2a4-c1f9-4691-a968-446c62800120.png)

**Comment by mjkapkan** [comment]
Hi, what do you have in mind by `SuspendedEV`?

**Comment by drc38** [comment]
> Hi, what do you have in mind by `SuspendedEV`?

`SuspendedEV` is when the vehicle has stopped the charge for some reason. In ovms the logic will set it to `timerwait`. 

Initially I thought the issue may have been the new SoC logic but it could be the start charge message does not work for AZE0 Leafs. Does the start charge button work for you after stopping the charge with the MITM code?

**Comment by mjkapkan** [comment]
Understood. The stop - start works perfectly on my 2013 MY. I heard it was working fine for @dalathegreat as well. Daniel can you double check when you have a chance?

**Comment by drc38** [comment]
@mjkapkan I've investigated a bit more and it seems it may be related to the new SoC code. To replicate the issue set a SoC limit and tolerance, wait for the charge to stop, raise SoC limit to above tolerance to initiate charge again (does not charge on my Leaf nor does using Start Charge).

If the SoC limit is not reached Stop Charge and then Start Charge work as expected.

**Comment by mjkapkan** [comment]
Hm, I tested this many times. Was working as expected. If you set the tolerance to 0 does it still do that? Also do you use charge to SOC, charge to Range or both? If so are you sure those other parameters did not conflict? You also should get a notification of why the charge is being started / stopped. What do you get in this case?

**Comment by drc38** [comment]
I am only using the charge to SoC, I will have to wait as the car is currently charged to test what happens is a tolerance is not set.

**Comment by drc38** [comment]
Looks like it may have been a glitch, so will close. Was working as expected today, see below:
![Screenshot_20220202-214333_Open Vehicle](https://user-images.githubusercontent.com/20024196/152120945-89c7c9fc-f5ae-4d47-a538-baef6192c10e.jpg)

**Comment by drc38** [comment]
This was from the previous attempt where it started to charge then stopped again after c. 1% charge:
![Screenshot_20220202-214857_Open Vehicle](https://user-images.githubusercontent.com/20024196/152122070-ea141ff4-30e7-4b05-9ae3-a02803c9695e.jpg)

**Comment by mjkapkan** [comment]
I think what happened was that allowed soc drop was set and thus prevented charge from starting. I will make a change to allow charge to start ignoring the allowed drop of the target SOC/Range is updated.

**Comment by mjkapkan** [comment]
Created #696
