### ISSUE TITLE
Editable PCB Files

### ISSUE THREAD

**Issue by Jamidd** [openvehicles/Open-Vehicle-Monitoring-System-3#713]
Hi, would it be possible to publish editable files to eventually modify and test custom options for the pcb. I know the schematics are published, but in pdf format is not easy to do anything. 

Thanks. 
Jaime

**Comment by markwj** [comment]
Unfortunately not. The contract manufacturer we use has their own systems to maintain the board layouts and they use a very expensive commercial PCB design tool. We have the schematics, and board layout PDFs, but the layouts themselves are not in a hobbyist format.
