### ISSUE TITLE
SSH "Unable to negotiate" (incl. workaround)

### ISSUE THREAD

**Issue by jollyjinx** [openvehicles/Open-Vehicle-Monitoring-System-3#745]
macOS ventura disabled the use of RSA keys for ssh by default. So a ssh results in:

```
tin>ssh  ovms3 -l admin
Unable to negotiate with 172.16.112.12 port 22: no matching host key type found. Their offer: ssh-rsa
```

You can work around this by adding rsa to the supported protocols in ssh with the **-oHostKeyAlgorithms=+ssh-rsa** option like this:
```
tin>ssh -oHostKeyAlgorithms=+ssh-rsa  ovms3 -l admin
admin@ovms3's password: 

Welcome to the Open Vehicle Monitoring System (OVMS) - SSH Console
Firmware: 3.3.003-17-g5d8f5771/ota_0/eap
Hardware: OVMS WIFI BLE BT cores=2 rev=ESP32/3; MODEM SIM7600

OVMS# 

```

**Comment by dexterbg** [comment]
This has already been documented in the user manual: https://docs.openvehicles.com/en/latest/userguide/console.html#ssh-console
