### ISSUE TITLE
US Store confusing

### ISSUE THREAD

**Issue by kallisti5** [openvehicles/Open-Vehicle-Monitoring-System-3#800]
The US store to buy the OVMS v3.3 is really confusing.   I'm refering people to buy the OVMS for their Bolt EV's, but the store just lists the base kit for the Roadster:

https://medlockandsons.com/product/ovms-v3/

Any options of updating the language to be less-Tesla roadster focused?

**Comment by markwj** [comment]
I will forward on your concerns to the store concerned. But as we do not run the store, we do not have any direct control on their listings.

**Comment by kallisti5** [comment]
For any future lurkers, this seemed to get me a good unit for my Bolt EV:

Select: "Roadster OVMS v3.3 Kit /SIM7600 4G"
Specify:  "Bolt EV ODB2 Cable pointing right"
