### ISSUE TITLE
2015 Nissan Leaf Door lock Command doesn't work. 

### ISSUE THREAD

**Issue by nismoman240sx** [openvehicles/Open-Vehicle-Monitoring-System-3#826]
I'm not sure if this is an issue or not, because it seems like everyone on the forums has the same issue. Is the door lock/unlock button not something that works with the Leaf? If it doesn't work, is it possible to get the option removed from the app?

**Comment by glynhudson** [comment]
It only works with 2016+ Leafs

**Comment by nismoman240sx** [comment]
Thank you!
