### ISSUE TITLE
Delete this page https://www.openvehicles.com/vehiclesupport

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#982]
This page is bad advertisement to the project. Its fully outdated, but if you use web search engines, you find it first. Even before you find the real one. Completely new people who never heard of this project do not know, that OVMSv1 and OVMSv2 are not recent any more wont search for the supported vehicles by OVMSv3. Instead they would just stop informing about OVMS because their vehicle is not supported based on the website information.

**Comment by markwj** [comment]
Page has been removed.
