### ISSUE TITLE
Create a new link named "Documentation" at the left pannel on https://www.openvehicles.com

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#988]
The left bar you open by pressing the hamburger menu (most people name this 3 lines to press "hamburger menu") have at the moment "About us" "Buy" "Forums" "Support" and so on. But "Documentation" that brings the users to the new and most important source of information about OVMS, https://docs.openvehicles.com , is missing. 
Could you create "Documentation" linking to https://docs.openvehicles.com so the people wont have use web search engines or look deeper into the website to find it?

**Comment by markwj** [comment]
OK. We have added the link.
