### ISSUE TITLE
Broken TLS HTTPS certificate on https://openvehicles.com/ (domain without the www.-subdomain)

### ISSUE THREAD

**Issue by fowi4hjte** [openvehicles/Open-Vehicle-Monitoring-System-3#989]
At the moment the certificate on https://openvehicles.com is broken. Its valid for www.charged.hk and charged.hk but not for the domain https://openvehicles.com . 
Additional information available for example here: https://www.ssllabs.com/ssltest/analyze.html?d=openvehicles.com

**Comment by markwj** [comment]
Thanks for the report. This has now been resolved. All of

http://openvehicles.com/
https://openvehicles.com/
http://www.openvehicles.com/

should redirect to

https://www.openvehicles.com/

and all should have the wildcard certificate presented.
