### ISSUE TITLE
Can't turn off SIMCOM power

### ISSUE THREAD

**Issue by slcasner** [openvehicles/Open-Vehicle-Monitoring-System-3#99]
On v3.0 hardware, in case that is significant:

OVMS# power simcom off
Power mode of simcom is now off
I (62232813) simcom: State: Enter PoweringOff state
I (62232813) gsm-ppp: Shutdown (direct)
I (62232813) gsm-nmea: Shutdown (direct)
I (62232813) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (62232823) simcom: Power Cycle
I (62242353) simcom: State timeout, transition to 1
I (62242353) simcom: State: Enter CheckPowerOff state
I (62253363) simcom: State: Enter PoweringOff state
I (62253363) gsm-ppp: Shutdown (direct)
I (62253363) gsm-nmea: Shutdown (direct)
I (62253363) simcom: Power Cycle
I (62253363) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (62263353) simcom: State timeout, transition to 1
I (62263353) simcom: State: Enter CheckPowerOff state
I (62274363) simcom: State: Enter PoweringOff state
I (62274363) gsm-ppp: Shutdown (direct)
I (62274363) gsm-nmea: Shutdown (direct)
I (62274363) simcom: Power Cycle
I (62274363) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (62284353) simcom: State timeout, transition to 1
I (62284353) simcom: State: Enter CheckPowerOff state
I (62295363) simcom: State: Enter PoweringOff state
I (62295363) gsm-ppp: Shutdown (direct)
I (62295363) gsm-nmea: Shutdown (direct)
I (62295363) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (62295363) simcom: Power Cycle
I (62305353) simcom: State timeout, transition to 1
I (62305353) simcom: State: Enter CheckPowerOff state
OVMS# simcom setstate PoweredOff
I (62314923) simcom: State: Enter PoweredOff state
I (62314923) gsm-mux: Stop MUX

This stops the power cycle loop for a while, but later it starts up again (not sure what is the trigger).
More info:

OVMS# simcom status
SIMCOM
  Network Registration: NotRegistered
  State: PoweredOff
  Ticker: 383
  User Data: 0

  Mux
    Status: down
    Open Channels: 0
    Framing Errors: 0
    Last RX frame: 0 sec(s) ago
    RX frames: 0
    TX frames: 0

  PPP
    Not Connected
    Last Error: Undefined

  GPS
    Status: disabled
    Time: disabled
    NMEA: GPS/GLONASS Not Connected
OVMS# config list auto
auto (readable writeable)
  ext12v: no
  init: yes
  modem: no
  obd2ecu: 
  server.v2: no
  server.v3: no
  vehicle.type: TR
  wifi.mode: client
  wifi.ssid.ap: OVMS
  wifi.ssid.client: Revelstoke
OVMS#

**Comment by dexterbg** [comment]
Steve, can you please add a log of that cycle at level verbose?

**Comment by slcasner** [comment]
Logging level for * set to verbose
I (82923353) simcom: State timeout, transition to 1
I (82923353) simcom: State: Enter CheckPowerOff state
V (82934353) simcom: tx: 41 54 0d 0a                                     | AT..            
D (82934353) simcom: tx scmd ch=0 len=4   : AT||
V (82934363) simcom: rx: 41 54 0d                                        | AT.             
I (82934363) simcom: State: Enter PoweringOff state
I (82934363) gsm-ppp: Shutdown (direct)
I (82934363) gsm-nmea: Shutdown (direct)
V (82934363) simcom: tx: f9 11 ff 17 41 54 2b 43 47 50 53 3d 30 0d 0a f3 | ....AT+CGPS=0...
V (82934363) simcom: tx: f9                                              | .               
I (82934373) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (82934373) simcom: Power Cycle
V (82934373) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
V (82934383) simcom: rx: 41 54 2b 43 47 50 53 3d 30 0d                   | AT+CGPS=0.      
V (82934393) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
I (82944353) simcom: State timeout, transition to 1
I (82944353) simcom: State: Enter CheckPowerOff state
V (82955353) simcom: tx: 41 54 0d 0a                                     | AT..            
D (82955353) simcom: tx scmd ch=0 len=4   : AT||
V (82955363) simcom: rx: 41 54 0d                                        | AT.             
I (82955363) simcom: State: Enter PoweringOff state
I (82955363) gsm-ppp: Shutdown (direct)
I (82955373) gsm-nmea: Shutdown (direct)
V (82955373) simcom: tx: f9 11 ff 17 41 54 2b 43 47 50 53 3d 30 0d 0a f3 | ....AT+CGPS=0...
V (82955373) simcom: tx: f9                                              | .               
I (82955383) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (82955383) simcom: Power Cycle
V (82955383) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
V (82955393) simcom: rx: 41 54 2b 43 47 50 53 3d 30 0d                   | AT+CGPS=0.      
V (82955393) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
I (82965353) simcom: State timeout, transition to 1
I (82965353) simcom: State: Enter CheckPowerOff state
V (82976353) simcom: tx: 41 54 0d 0a                                     | AT..            
D (82976353) simcom: tx scmd ch=0 len=4   : AT||
V (82976363) simcom: rx: 41 54 0d                                        | AT.             
I (82976363) simcom: State: Enter PoweringOff state
I (82976363) gsm-ppp: Shutdown (direct)
I (82976373) gsm-nmea: Shutdown (direct)
V (82976373) simcom: tx: f9 11 ff 17 41 54 2b 43 47 50 53 3d 30 0d 0a f3 | ....AT+CGPS=0...
V (82976373) simcom: tx: f9                                              | .               
I (82976383) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (82976383) simcom: Power Cycle
V (82976383) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
V (82976393) simcom: rx: 41 54 2b 43 47 50 53 3d 30 0d                   | AT+CGPS=0.      
V (82976403) simcom: rx: 0d 0a 4f 4b 0d 0a                               | ..OK..          
I (82986353) simcom: State timeout, transition to 1
I (82986353) simcom: State: Enter CheckPowerOff state

**Comment by dexterbg** [comment]
Very strange, your modem echos all commands even after a power cycle, so the CheckPowerOff state assumes it's still alive. I cannot reproduce this even with an explicit `simcom cmd ATE1` before `power simcom off`, my modem doesn't echo anything in powered off state.

You can try giving `simcom cmd ATE0` before power-off, but this may be a hardware issue. Maybe TX and RX have a shortcut?

**Comment by slcasner** [comment]
I have just now flashed to OTA0 the 3.1.003 image.  It starts up fine and powers off the modem:

I (735) cpu_start: Pro cpu up.
I (735) cpu_start: Starting app cpu, entry point is 0x400811c8
0x400811c8: call_start_cpu1 at /Users/casner/src/github/esp-idf/components/esp32/./cpu_start.c:243

I (719) cpu_start: App cpu up.
I (738) heap_init: Initializing. RAM available for dynamic allocation:
I (745) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (751) heap_init: At 3FFBBB20 len 000244E0 (145 KiB): DRAM
I (757) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (763) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (771) heap_init: At 400929F8 len 0000D608 (53 KiB): IRAM
I (776) cpu_start: Pro cpu start user code
I (122) ovms_main: Set default logging level for * to INFO
I (123) command: Initialising COMMAND (1000)
I (124) boot: Initialising BOOT (1100)
I (128) boot: Boot #1 reasons for CPU0=12 and CPU1=12
I (133) boot: Soft reset by user
I (137) events: Initialising EVENTS (1200)
I (142) config: Initialising CONFIG (1400)
I (147) time: Initialising TIME (1500)
I (152) script: Initialising SCRIPTS (1600)
I (156) script: Using DUKTAPE javascript engine
I (162) metrics: Initialising METRICS (1810)
I (166) metrics: Expanding DUKTAPE javascript engine
I (177) notify: Initialising NOTIFICATIONS (1820)
I (178) notify: Registered notification type info
I (183) notify: Registered notification type error
I (188) notify: Registered notification type alert
I (194) notify: Registered notification type data
I (199) location: Initialising LOCATIONS (1900)
I (205) location: Expanding DUKTAPE javascript engine
I (210) vehicle: Initialising VEHICLE Factory (2000)
I (216) pcp: Initialising POWER (4000)
I (220) max7317: Initialising MAX7317 EGPIO (4200)
I (225) sdcard: Initialising SD CARD (4400)
I (230) ota: Initialising OTA (4400)
I (235) can: Initialising CAN (4500)
I (240) simcom: Initialising SIMCOM (4600)
I (244) test: Initialising TEST (5000)
I (248) ovms-module: Initialising MODULE (5100)
I (253) vfs: Initialising VFS (5200)
I (258) ovms-server: Initialising OVMS Server (6000)
I (263) ovms-server-v2: Initialising OVMS V2 Server (6100)
I (269) ovms-server-v3: Initialising OVMS V3 Server (6200)
I (276) obd2ecu: Initialising OBD2ECU (7000)
I (281) canopen: Initialising CANopen (7000)
I (286) esp32wifi: Initialising ESP32WIFI (8000)
I (291) ovms-mdns: Initialising MDNS (8100)
I (296) webserver: Initialising WEBSERVER (8200)
I (302) ssh: Initialising SSH (8300)
I (305) re: Initialising RE Tools (8800)
I (310) netmanager: Initialising NETMANAGER (8999)
I (317) v-track: Registering Vehicle: TRACK (9000)
I (321) v-teslaroadster: Registering Vehicle: Tesla Roadster (9000)
I (327) v-teslamodels: Registering Vehicle: Tesla Model S (9000)
I (334) v-twizy: Registering Vehicle: Renault Twizy (9000)
I (340) v-obdii: Registering Vehicle: OBDII (9000)
I (346) v-none: Registering Vehicle: NONE (9000)
I (351) v-nissanleaf: Registering Vehicle: Nissan Leaf (9000)
I (358) v-kiasoulev: Registering Vehicle: Kia Soul EV (9000)
I (364) v-demo: Registering Vehicle: DEMO (9000)
I (369) version: Initialising Versioning (9900)
I (378) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (424) ovms_main: Executing on CPU core 0
I (424) ovms_main: Mounting CONFIG...
I (994) ovms_main: Registering default configs...
I (994) ovms_main: Starting HOUSEKEEPING...
I (994) housekeeping: Initialising HOUSEKEEPING Framework...
I (1054) housekeeping: Executing on CPU core 1
I (1054) housekeeping: reset_reason: cpu0=12, cpu1=12
I (1054) housekeeping: Initialising WATCHDOG...
I (1064) housekeeping: Starting PERIPHERALS...
I (1064) peripherals: Initialising OVMS Peripherals...
I (1074) peripherals:   TCP/IP Adaptor
I (1074) peripherals:   ESP32 system
I (1084) peripherals:   SPI bus
I (1084) peripherals:   MAX7317 I/O Expander
I (1084) peripherals:   ESP32 CAN
I (1094) peripherals:   ESP32 WIFI
I (1094) peripherals:   ESP32 ADC
I (1094) peripherals:   MCP2515 CAN 1/2
I (1104) peripherals:   MCP2515 CAN 2/2
I (1114) peripherals:   SD CARD
I (1114) peripherals:   SIMCOM MODEM
I (1114) gpio: GPIO[16]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1124) gpio: GPIO[17]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1134) uart: queue free spaces: 10
I (1134) ext12v: Powering off external 12V devices
I (1144) housekeeping: Auto init ext12v (free: 140600 bytes)
I (1144) housekeeping: Auto init wifi (free: 140600 bytes)
I (1154) esp32wifi: Powering up WIFI driver
I (1154) wifi: wifi firmware version: ebd3e5d
I (1164) wifi: config NVS flash: enabled
I (1164) wifi: config nano formating: disabled
I (1164) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1174) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (1204) wifi: Init dynamic tx buffer num: 16
I (1204) wifi: Init data frame dynamic rx buffer num: 16
I (1204) wifi: Init management frame dynamic rx buffer num: 16
I (1204) wifi: wifi driver task: 3ffdec70, prio:23, stack:4096
I (1214) wifi: Init static rx buffer num: 4
I (1214) wifi: Init dynamic rx buffer num: 16
I (1224) wifi: wifi power manager task: 0x3ffdfd44 prio: 21 stack: 2560
I (1284) phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0
I (1294) wifi: mode : sta (30:ae:a4:37:1b:84)
I (1294) housekeeping: Auto init modem (free: 122028 bytes)
I (1294) housekeeping: Auto init vehicle (free: 120912 bytes)
I (1304) v-teslaroadster: Tesla Roadster v1.x, v2.x and v3.0 vehicle module
I (1314) housekeeping: Auto init obd2ecu (free: 117212 bytes)
I (1314) housekeeping: Auto init server v2 (free: 117212 bytes)
I (1324) housekeeping: Auto init server v3 (free: 117212 bytes)
I (1324) housekeeping: Auto init done (free: 117212 bytes)
I (1334) housekeeping: Starting USB console...
I (1344) uart: queue free spaces: 30

Welcome to the Open Vehicle Monitoring System (OVMS) - Async Console
Firmware: 3.1.003/ota_0/main
Hardware: OVMS WIFI BLE BT cores=2 rev=ESP32/1
I (1354) ovms-mdns: Starting MDNS

I (2054) simcom: State: Enter CheckPowerOff state
I (3704) wifi: n:1 0, o:1 0, ap:255 255, sta:1 0, prof:1
I (4364) wifi: state: init -> auth (b0)
I (4374) wifi: state: auth -> assoc (0)
I (4374) wifi: state: assoc -> run (10)
I (4414) wifi: connected with Revelstoke, channel 1
I (7374) wifi: pm start, type:0
I (11054) housekeeping: System considered stable (free: 94556 bytes)
I (11134) simcom: State: Enter PoweringOff state
I (11134) gsm-ppp: Shutdown (direct)
I (11134) gsm-nmea: Shutdown (direct)
I (11134) simcom: Power Cycle
I (22054) simcom: State timeout, transition to 1
I (22054) simcom: State: Enter CheckPowerOff state
I (37054) simcom: State timeout, transition to 13
I (37054) simcom: State: Enter PoweredOff state
I (37054) gsm-mux: Stop MUX
I (42554) event: sta ip: 192.168.1.84, mask: 255.255.255.0, gw: 192.168.1.254
I (42554) netmanager: Interface priority is st1 (192.168.1.84/255.255.255.0 gateway 192.168.1.254)
I (42554) netmanager: WIFI client up (with MODEM down): starting network with WIFI client
I (42554) time: Starting SNTP client
I (42564) esp32wifi: STA got IP with SSID: Revelstoke, MAC: 30:ae:a4:37:1b:84, IP: 192.168.1.84, mask: 255.255.255.0, gw: 192.168.1.254
I (42574) webserver: Launching Web Server
I (42584) ssh: Launching SSH Server
I (127184) webserver: HTTP GET /
I (129914) webserver: HTTP GET /apple-touch-icon.png
I (129964) webserver: HTTP GET /cfg/firmware
I (143424) webserver: HTTP POST /cfg/firmware
I (143434) webserver: HandleLogin: 'admin' logged in, sid 5a21b1b51ef4fd8c
I (143564) webserver: HTTP GET /menu
I (143564) webserver: HTTP GET /cfg/firmware
OVMS> simcom status
SIMCOM
  Network Registration: NotRegistered
  State: PoweredOff
  Ticker: 267
  User Data: 0

  Mux
    Status: down
    Open Channels: 0
    Framing Errors: 0
    Last RX frame: 0 sec(s) ago
    RX frames: 0
    TX frames: 0

  PPP
    Not Connected
    Last Error: Undefined

  GPS
    Status: disabled
    Time: disabled
    NMEA: GPS/GLONASS Not Connected
OVMS>

**Comment by markwj** [comment]
Is this ok now? Seems ok for me.

**Comment by slcasner** [comment]
On Tue, 1 May 2018, Mark Webb-Johnson wrote:

> Is this ok now? Seems ok for me.

No, it still loops.  If I issue "simcom setstate PoweredOff" I can
stop the loop for a while.  Not sure what event restarts it.  The
power is not off, though, this just stops the code that tries to cycle
power.

The blue LED is on.  When I issue "power simcom off" should that turn
it off?  It does not.

                                                        -- Steve

**Comment by slcasner** [comment]
Nevermind, this was my fault.  I was trimming down the configuration to minimize RAM usage on my v3.0 hardware and that included CONFIG_OVMS_COMP_MAX7317.  Tonight I read the simcom.cpp code to discover that the power control for the SIMCOM modem goes through the MAX7317, so that is why the power would not turn off.
